<?php

namespace App\Imports;

use App\Models\Data_siswa;

use Maatwebsite\Excel\Concerns\ToModel;
use Maatwebsite\Excel\Concerns\Importable;
use Maatwebsite\Excel\Concerns\WithHeadingRow;

class DataImport implements ToModel, WithHeadingRow
{
    use Importable;

    public function model(array $row)
    {
        return new Data_siswa([
        'no_formulir'               => $row['NO_FORMULIR'],
        'ppdb_id'                   => $row['PPDB_ID'],
    	'tahun_ajaran'              => $row['TAHUN_AJARAN'],
    	'tanggal_pendaftaran'       => $row['TANGGAL_PENDAFTARAN'],
    	'status_siswa'              => $row['STATUS_SISWA'],
    	'nama_lengkap'              => $row['NAMA_LENGKAP'],
    	'jenis_kelamin'             => $row['JENIS_KELAMIN'],
    	'nisn'                      => $row['NISN'],
    	'kitas'                     => $row['KITAS'],
    	'tempat_lahir'              => $row['TEMPAT_LAHIR'],
    	'tanggal_lahir'             => $row['TANGGAL_LAHIR'],
    	'akta_kelahiran'            => $row['AKTA_KELAHIRAN'],
    	'agama'                     => $row['AGAMA'],
    	'kewarganegaraan'           => $row['KEWARGANEGARAAN'],
    	'nama_negara'               => $row['NAMA_NEGARA'],
    	'berkebutuhan_khusus'       => $row['BERKEBUTUHAN_KHUSUS'],
		'berkebutuhan_khusus_2'     => $row['BERKEBUTUHAN_KHUSUS_2'],
    	'alamat_jalan'              => $row['ALAMAT_JALAN'],
    	'rt'                        => $row['RT'],
    	'rw'                        => $row['RW'],
    	'nama_dusun'                => $row['NAMA_DUSUN'],
        'nama_kelurahan'            => $row['NAMA_KELURAHAN'],
		'nama_kelurahan_2'          => $row['NAMA_KELURAHAN_2'],
    	'kecamatan'                 => $row['KECAMATAN'],
    	'kode_pos'                  => $row['KODE_POS'],
    	'tempat_tinggal'            => $row['TEMPAT_TINGGAL'],
    	'moda_transportasi'         => $row['MODA_TRANSPORTASI'],
    	'nomor_kks'                 => $row['NOMOR_KKS'],
    	'anak_keberapa'             => $row['ANAK_KEBERAPA'],
    	'penerima_kps_pkh'          => $row['PENERIMA_KPS_PKH'],
    	'no_kph_pkh'                => $row['NO_KPH_PKH'],
    	'usulan_dari_sekolah'       => $row['USULAN_DARI_SEKOLAH'],
    	'kip'                       => $row['KIP'],
    	'nomor_kip'                 => $row['NOMOR_KIP'],
        'nama_kip'                  => $row['NAMA_KIP'],
    	'kartu_KIP'                 => $row['KARTU_KIP'],
    	'alasan_layak_pip'          => $row['ALASAN_LAYAK_PIP'],
    	'bank'                      => $row['BANK'],
    	'no_rekening'               => $row['NO_REKENING'],
    	'rekening_atas_nama'        => $row['REKENING_ATAS_NAMA'],
    	'nama_ayah'                 => $row['NAMA_AYAH'],
    	'nik_ayah'                  => $row['NIK_AYAH'],
    	'tahun_lahir_ayah'          => $row['TAHUN_LAHIR_AYAH'],
    	'pendidikan_ayah'           => $row['PEKERJAAN_AYAH'],
    	'pekerjaan_ayah'            => $row['PEKERJAAN_AYAH'],
    	'penghasilan_bulanan_ayah'  => $row['PENGHASILAN_BULANAN_AYAH'],
    	'berkebutuhan_khusus_ayah'  => $row['BERKEBUTUHAN_KHUSUS_AYAH'],
        'nama_Ibu'                  => $row['NAMA_IBU'],
    	'nik_Ibu'                   => $row['NIK_IBU'],
        'tahun_lahir_ibu'           => $row['TAHUN_LAHIR_IBU'],
    	'pendidikan_ibu'            => $row['PENDIDIKAN_IBU'],
    	'pekerjaan_ibu'             => $row['PEKERJAAN_IBU'],
        'penghasilan_bulanan_ibu'   => $row['PENGHASILAN_BULANAN_IBU'],
    	'berkebutuhan_khusus_ibu'   => $row['BERKEBUTUHAN_KHUSUS_IBU'],
    	'nama_wali'                 => $row['NAMA_WALI'],
    	'nik_wali'                  => $row['NIK_WALI'],
    	'tahun_lahir_wali'          => $row['TAHUN_LAHIR_WALI'],
    	'pendidikan_wali'           => $row['PENDIDIKAN_WALI'],
    	'pekerjaan_wali'            => $row['PEKERJAAN_WALI'],
		'penghasilan_bulanan_wali'  => $row['PENGHASILAN_BULANAN_WALI'], 
        'telepon_rumah'             => $row['TELEPON_RUMAH'],
        'nomor_hp'                  => $row['NOMOR_HP'],
        'email'                     => $row['EMAIL'], 
        'jenis_ekstrakulikuler'     => $row['JENIS_EKSTRAKULIKULER'],  
        'tinggi_badan'              => $row['TINGGI_BADAN'],  
        'berat_badan'               => $row['BERAT_BADAN'], 
        'jarak_tempat'              => $row['JARAK_TEMPAT'], 
        'waktu_tempuh'              => $row['WAKTU_TEMPAT'],  
        'saudara_kandung'           => $row['SAUDARA_KANDUNG'],
 
		'jurusan'                   => $row['JURUSAN'],
        'jenis_pendaftaran'         => $row['JENIS_PENDAFTARAN'],
        'nis'                       => $row['NIS'],
        'tanggal_masuk_sekolah'     => $row['TANGGAL_MASUK_SEKOLAH'],
        'asal_sekolah'              => $row['ASAL_SEKOLAH'],
        'nomor_peserta_ujian'       => $row['NOMOR_PESERTA_UJIAN'],
        'no_seri_ijazah'            => $row['NO_SERI_IJAZAH'],
		'no_seri_skhun'             => $row['NO_SERI_SKHUN'],
		'keluar_karena'             => $row['KELUAR_KARENA'],
		'tanggal_keluar'            => $row['TANGGAL_KARENA'],
		'alasan'                    => $row['ALASAN'],

		'persetujuan'               => $row['PERSETUJUAN'],
                        
		'jenis_1'                   => $row['JENIS_1'],
		'tingkat_1'                 => $row['TINGKAT_1'],
        'nama_prestasi_1'           => $row['NAMA_PRESTASI_1'],
        'tahun_1'                   => $row['TAHUN_1'],
		'penyelenggara_1'           => $row['PENYELENGGARA_1'],
		'jenis_2'                   => $row['JENIS_2'],
		'tingkat_2'                 => $row['TINGKAT_2'],
		'nama_prestasi_2'           => $row['NAMA_PRESTASI_2'],
		'tahun_2'                   => $row['TAHUN_2'],
		'penyelenggara_2'           => $row['[PENYELENGGARA_2]'],
		'jenis_3'                   => $row['JENIS_3'],
		'tingkat_3'                 => $row['TINGKAT_3'],
		'nama_prestasi_3'           => $row['NAMA_PRESTASI_3'],
		'tahun_3'                   => $row['TAHUN_3'],
		'penyelenggara_3'           => $row['PENYELENGGARA_3'],
		'jenis_1_0'                   => $row['JENIS_1_0'],
		'keterangan_1'              => $row['KETERANGAN_1'],
		'tahun_mulai_1'             => $row['TAHUN_MULAI_1'],
		'tahun_selesai_1'           => $row['TAHUN_SELESAI_1'],
		'jenis_2_0'                   => $row['JENIS_2_0'],
		'keterangan_2'              => $row['KETERANGAN_2'],
		'tahun_mulai_2'             => $row['TAHUN_MULAI_2'],
		'tahun_selesai_2'           => $row['TAHUN_SELESAI_2'],
		'jenis_3_0'                   => $row['JENIS_3_0'],
		'keterangan_3'              => $row['KETERANGAN_3'],
		'tahun_mulai_3'             => $row['TAHUN_MULAI_3'],
		'tahun_selesai_3'           => $row['TAHUN_SELESAI_3']
        ]);
    }
}